before_script:
  - pod --version
  - pod repo update baidao-ios-ytx-pod-specs

stages:
  - test
  - lint
  - release

test:
  tags:
    - iOS
  stage: test
  script:
    - YTX_PROJECT_NAME=${PWD##*/}
    - cd Example
    - pwd
    - time pod install --verbose
    - time xcodebuild test -workspace $YTX_PROJECT_NAME.xcworkspace -scheme $YTX_PROJECT_NAME-Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' | xcpretty

release:
  tags:
    - iOS
  only:
    - master
  stage: release
  script:
    - time sh pod_package.sh
    - time sh lint.sh
    - time sh zip.sh
    - time sh buildpod.sh
    - time sh release_pb_app.sh

lint:
  tags:
    - iOS
  stage: lint
  except:
    - master
  script:
    - time sh pod_package.sh
    - time sh lint.sh