before_script:
  - pod --version

stages:
  - test
  - lint
  - release

test:
  tags:
    - iOS
  only:
    - master
  stage: test
  script:
    - YTX_PROJECT_NAME=${PWD##*/}
    - cd Example
    - pwd
    - pod install --verbose
    - xcodebuild test -workspace $YTX_PROJECT_NAME.xcworkspace -scheme $YTX_PROJECT_NAME-Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' | xcpretty

release:
  tags:
    - iOS
  only:
    - master
  stage: release
  script:
    - sh pod_package.sh
    - sh lint.sh
    - sh buildpod.sh
    - sh release_pb_app.sh

lint:
  tags:
    - iOS
  stage: lint
  except:
    - master
  script:
    - sh pod_package.sh
    - sh lint.sh